### ISSUE TITLE
Set my own list of countries?

### ISSUE THREAD

**Issue by RonAlmog** [nikhiln/ngx-international-phone-number#14]
I don't want to show all the countries in the list, and instead I have my own list of countries.
Is there a way to do that?

**Comment by khan8698** [comment]
+1

**Comment by choopage** [comment]
Submit a PR?

**Comment by choopage** [comment]
Could you add me @choopage as collaborator? I would like to contribute to
this module.

**Comment by nikhiln** [comment]
@choopage Aren't you able to open PR? If you are looking to help managing this repo, do let me know.
