### ISSUE TITLE
Doesn't work with Reactive form, need to be able to work with FormControlName

### ISSUE THREAD

**Issue by azosyk** [nikhiln/ngx-international-phone-number#18]
The filed  "international-phone-number"

> ` <international-phone-number>
 </international-phone-number>  `

is part of the big Reactive form and FormControlName need to be used to send data to the service, but it doesn't work.
Please, suggests workarounds if any.

**Comment by choopage** [comment]
i tried. it worked.

**Comment by choopage** [comment]
This is what I am using.

```
 <international-phone-number [placeholder]="question.label" [formControlName]="question.key" [id]="question.key"
                                  [maxlength]="30" [defaultCountry]="'sg'" [required]="true"
                                  name="phone_number"></international-phone-number>
```
