### ISSUE TITLE
Problem with Angular Material Input field 

### ISSUE THREAD

**Issue by ils-nikhilp** [nikhiln/ngx-international-phone-number#19]
I have tried a lot to customize the field same as angular-material input field with the floating label. But unable to customize it. So, can you provide the way to customize it same as the material field which follows all the UI functionality same as material field.

**Comment by nikhiln** [comment]
@ils-nikhilp You can provide PR if you can add this easily.

**Comment by ils-nikhilp** [comment]
@nikhiln  
Okay, I am correcting my above question for more clarification.
To use this directive with the material text field directive (which is in Angular-6) won't working. So how to use ''ngx-inernational-phone-number'' directive in angular-material.

Here is the code how we use the material input field;
`<mat-form-field>
    <input matInput placeholder="Moblile number *" formControlName="mobileNumber" 
    [value]="tForm.get('userData.mobileNumber').value">
    
    <mat-error *ngIf="tForm.hasError('required', 'userData.mobileNumber')">
      * Mobile number is required.
    </mat-error>
</mat-form-field>`

How can I use 'ngx-international-phone-number' directive with the above code?
So, that it can look like the below images.

![mobile-validation01](https://user-images.githubusercontent.com/29393750/49921581-02e6c480-fed4-11e8-93cf-f610428e3271.PNG)
![mobile-validation02](https://user-images.githubusercontent.com/29393750/49921582-02e6c480-fed4-11e8-8a6f-343034985179.PNG)

**Comment by nikhiln** [comment]
@ils-nikhilp This is more like angular material design specific code implementation. This is not supported at the moment.
