### ISSUE TITLE
Problem with autofocus after selection of the country code

### ISSUE THREAD

**Issue by kaushik-nimble** [nikhiln/ngx-international-phone-number#2]
I am using Angular 5 and I have implemented this plugin here

https://wynnify.herokuapp.com/      -->   REGISTER HERE

When you are in register and select the country it will not focus the textbox, user needs to manually click on textbox to get the focus on the textbox.

Is there something I am missing? 

Thank you in advance.

**Comment by nikhiln** [comment]
This seems to be an issue. Would take a look and fix it.

**Comment by azeemkhalid04** [comment]
@nikhiln I have upgraded to the latest version "1.0.4" and this issue still exists. User has to click on Textbox to start typing.
