### ISSUE TITLE
Problem with Allowed Countries messing up the package

### ISSUE THREAD

**Issue by jainarihant** [nikhiln/ngx-international-phone-number#20]
I am using:
"@angular/animations": "^4.4.7",
    "@angular/cdk": "^5.2.5",
    "@angular/cli": "^1.7.4",
    "@angular/common": "^5.2.11",
    "@angular/compiler": "^5.2.11",
    "@angular/compiler-cli": "^5.2.11",
    "@angular/core": "^5.2.11",
    "@angular/forms": "^5.2.11",
    "@angular/http": "^5.2.11",
    "@angular/language-service": "^5.2.11",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.2.11",
    "@angular/platform-browser-dynamic": "^5.2.11",
    "@angular/router": "^5.2.11"

And the current version of "ngx-international-phone-number": "~1.0.1", I require https resources for the flags so I am using this new version.
The package gets installed properly, but when I run my angular app I get this:
`ERROR in node_modules/ngx-international-phone-number/phone-number.component.d.ts(13,23): error TS1122: A tuple type element list cannot be empty.`

I dug a bit on this and found that variable allowedCountries: [ ] has been wrongly type-casted in the build. It should have been allowedCountries: Country[ ]. 

I'll try to put up a PR for this.

**Comment by ronrumao** [comment]
@nikhiln if you provide me with the access to create branch and open a PR, maybe I'll raise a PR for the same issue.

**Comment by nikhiln** [comment]
@ronrumao @jainarihant You guys should be able to fork and open up PR.

**Comment by jainarihant** [comment]
@nikhiln ok I'll raise a PR.

**Comment by jainarihant** [comment]
Fixed in #21

**Comment by ronrumao** [comment]
@nikhiln the changes related to #21 are merged but not published yet.
Is there any need to bump version or manually publish the changes? As the version in the npm repository is 1.0.1 and is published 21 days ago( which is older than #21 changes)

**Comment by vitorolivg** [comment]
@nikhiln could you please bump the version?
