### ISSUE TITLE
Country flag shown twice

### ISSUE THREAD

**Issue by quekqh** [nikhiln/ngx-international-phone-number#28]
Bugs to fix: Australia and Azerbaijian shown twice in the dropdown. Also, if number is keyed in manually, wrong flag is shown e.g. typing in Aaland's country code shows another flag

**Comment by nikhiln** [comment]
I have removed the duplicate countries. Currently we are identifying the flag based on dial code and since Aaland and Finland shares same dial code, it's picking up first one it finds there. There is similar issue opened here #3
