### ISSUE TITLE
question about style

### ISSUE THREAD

**Issue by infinitytn** [nikhiln/ngx-international-phone-number#30]
i am trying to use it and it works fine but can you give us a bit more style option?

for example

currently the dropdown is centered and it takes a bit of space
can u do left align ?

also in mobile it goes like this..

![image](https://user-images.githubusercontent.com/31636309/52466717-97189380-2bc6-11e9-85b7-d4dd96a47868.png)

i'm not sure how to do styling but if you can let me know how i can just try to apply css on this..

**Comment by nikhiln** [comment]
@infinitytn You should be able to override any styles in your component styling easily. I would be happy to review and merge PR regarding the style.
