### ISSUE TITLE
Text can be pasted in to Phone number field

### ISSUE THREAD

**Issue by VShkotin** [nikhiln/ngx-international-phone-number#38]
In case if user copy some text and then click right mouse button on input and choose "Paste" (or Edit/Paste in browser menu) -> text will be added into "onlyNumber" field
![image](https://user-images.githubusercontent.com/29312565/56499124-b0668600-650d-11e9-85f2-389dd1605c8c.png)

**Comment by choopage** [comment]
This is fixed https://github.com/esoyke/ngx-international-phone-number2

**Comment by VShkotin** [comment]
> This is fixed https://github.com/esoyke/ngx-international-phone-number2

This was fixed on April 22 https://github.com/nikhiln/ngx-international-phone-number/pull/39 :)

**Comment by VShkotin** [comment]
Sorry, forgot to close this issue
