### ISSUE TITLE
Reset the flag button after choosing some flag even input value is empty or null

### ISSUE THREAD

**Issue by Michaelwan777** [nikhiln/ngx-international-phone-number#49]
Hi! I've used this library for my angular project. It works like a charm. But the phone input's flag button can't be reset even my reactive form input value has been emptied or nullified. It still remains as the previously chosen flag.

Reproduction for this problem: 
![Screenshot (65)](https://user-images.githubusercontent.com/30439261/61025793-51b1f980-a3e4-11e9-9d12-1b207d5c4c84.png)

Any help is appreciated! Thank you in advance.

**Comment by nikhiln** [comment]
@Michaelwan777 You can use defaultCountry input to specify any default country you would like to set after reset.

**Comment by Michaelwan777** [comment]
Yep, Thank you @nikhiln!
