### ISSUE TITLE
(copying) cmd + c doesn't work in the input

### ISSUE THREAD

**Issue by eso32** [nikhiln/ngx-international-phone-number#55]
Hey,

just tried in my project and in this example - https://stackblitz.com/edit/angular-ngx-international-phone-number - copying doesn't work when you use shortcut cmd + c. Any idea why? Pasting and coping by using context menu works fine.

OS: macOs 10.14.5
browser: Chrome/76.0.3809.100

**Comment by choopage** [comment]
@esoyke might fix this for you. https://github.com/esoyke/ngx-international-phone-number2
Put this there. He might help.

**Comment by filipemendes1994** [comment]
This PR (#64) fixs this problem. Let's wait for review :)
