### ISSUE TITLE
Not able to publish the code in ASPNET CORE angular js 4 environment

### ISSUE THREAD

**Issue by dotnetleader** [nikhiln/ngx-international-phone-number#6]
Error getting during publish
 
The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code  

npm shrinkwrap.JSON UPDATED and there after it not allowing the application to publish
local on debug it is working well

**Comment by nikhiln** [comment]
I am not sure if it's specific to ASP.NET Core. If you are getting same issue with AOT mode, please feel free to reopen this issue.
