### ISSUE TITLE
Standardise ISO 3166

### ISSUE THREAD

**Issue by choopage** [nikhiln/ngx-international-phone-number#62]
> defaultCountryCode : An ISO 639-1 country code can be provided to set default country selected.

https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

I am really confused. ISO 639-1 is not country codes. ISO 3166 is.
Furthermore, it should upper case. Not lower case.

It's really confusing.

**Comment by nikhiln** [comment]
It's fixed now.
